/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.edu.eaut.lab4;

import java.util.List;
import javax.swing.*; 
/**
 *
 * @author edoga
 */
public class worker extends javax.swing.JFrame {

    /**
     * Creates new form worker
     */
    public worker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_second = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lb_remaining = new javax.swing.JLabel();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WORKER");

        btn_start.setText("Bắt đầu đếm");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        jLabel1.setText("Thời gian bắt đầu");

        lb_remaining.setText("Thời gian còn lại");

        btn_cancel.setText("Hủy đếm");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(txt_second)
                    .addComponent(lb_remaining)
                    .addComponent(jLabel1)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_second, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_remaining)
                .addGap(18, 18, 18)
                .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private SwingWorker<Void, Integer> worker;
    
    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        startCountdown();
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        cancelCountdown();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void startCountdown() { 
        int seconds; 
        try { 
            seconds = Integer.parseInt(txt_second.getText().trim()); 
            if (seconds <= 0) { 
                JOptionPane.showMessageDialog(this, "Số giây phải lớn hơn 0"); 
                return; 
            } 
        } catch (NumberFormatException ex) { 
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số nguyên hợp lệ"); 
            return; 
        } 
 
        btn_start.setEnabled(false); 
        btn_cancel.setEnabled(true);
        
        worker = new SwingWorker<>() { 
            @Override 
            protected Void doInBackground() throws Exception { 
                for (int i = seconds; i >= 0; i--) { 
                    publish(i); 
                    Thread.sleep(1000); 
                    if (isCancelled()) {
                        break;
                    }
                } 
                return null; 
            } 
 
            @Override 
            protected void process(List<Integer> chunks) { 
                int value = chunks.get(chunks.size() - 1);               
                lb_remaining.setText("Thời gian còn lại: " + value + " giây"); 
            } 
 
            @Override 
            protected void done() { 
                btn_start.setEnabled(true); 
                if (isCancelled()) {
                    JOptionPane.showMessageDialog(null, "Đã hủy đếm ngược!");
                } else {
                    JOptionPane.showMessageDialog(worker.this, "Hoàn thành!"); 
                }           
            } 
        }; 
        worker.execute(); 
    } 
    
    private void cancelCountdown(){
        worker.cancel(true);
        btn_start.setEnabled(true);     
        btn_cancel.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new worker().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lb_remaining;
    private javax.swing.JTextField txt_second;
    // End of variables declaration//GEN-END:variables
}
